### PR TITLE
Toggle Grouping Feature

### PR DESCRIPTION
**Pull request by KaifHalak**
Created the UI 

UI-1

UI-2

UI-3

UI-4

Can you please check if I used grids properly (under .groups-container)? Its my first time using them.

A "group" div element (dummy group) is present in the html document for testing purposes (to see how the groups will look like)

PROBLEM:
As you add more groups, the size of the row reduces instead of enabling the side scroll. I tried tinkering with the css, but I couldn't find an elegant solution

PS: Don't be shy to criticize my work  👁️👄👁️

Will soon push the script changes

### CODE REVIEW

**Comment by AdamKmet1997** [comment]
See the second picture you attached, jw why is there big gap between first row and second row?

**Comment by AdamKmet1997** [comment]
In my opinion we don't need to show empty container saying no groups yet, only show that section when there are groups available, the container should expand with the number of groups ...more groups == bigger extension size if you get me...instead of fixed height

**Comment by AdamKmet1997** [comment]
Could be hard to implement but we could have pagination?

So only show 4 rows of 2 
If more the make a 2nd page?

Or is that bad design? Just being conscious of height of the extension for users that have loads of groups

**Comment by AdamKmet1997** [comment]
Settings button is nice to have, what's in it? Maybe have it on top right instead?

**Comment by KaifHalak** [comment]
> See the second picture you attached, jw why is there big gap between first row and second row?

Yeah.. this was my first time using grid layout. I can probably fix that using flex boxes

>In my opinion we don't need to show empty container saying no groups yet, only show that section when there are groups available

Hmm.. then there is a possibility where the user may not know that such a feature exists? (disabling auto grouping for certain groups). By showing "No groups" would indicate that there is something more to groups (I might be wrong as well)


>Could be hard to implement but we could have pagination?

We can do 3 things:
1) Increase the size
2) Pagination
3) Using a scroll bar (once certain number of rows are reached)

Pagination is a good idea as we wont need to use the ugly scroll bar. I will see what I can do.

>Settings button is nice to have, what's in it? Maybe have it on top right instead?

Its used to toggle between the first and second picture (main menu and settings)


I personally think it's a good idea to first prioritize implementing the core functionality  and we can always spend more time to improving the UI later. The code for implementing functionality should remain relatively unchanged regardless of UI improvements. However, if you prefer to work on the UI first, I'm open to that.

**Comment by AdamKmet1997** [comment]
Yea I mean there's no rush in release so like we can get it done in one go.... if the gear is to switch between pages maybe when on main page have home.icon and when in settings page have gear icon?


Fair point with user might not know about the feature...let's think about this so

But technically when user clicks on group my tabs button he will create groups and that section will appear while the extension is still open so they'll see it straight away... so only time that section won't exist is when you open brand new browser and have never clicked the button if you get me

**Comment by AdamKmet1997** [comment]
Fair point with user might not know about the feature...let's think about this so

But technically when user clicks on group my tabs button he will create groups and that section will appear while the extension is still open so they'll see it straight away... so only time that section won't exist is when you open brand new browser and have never clicked the button if you get me

**Comment by KaifHalak** [comment]
> But technically when user clicks on group my tabs button he will create groups and that section will appear while the extension is still open so they'll see it straight away... so only time that section won't exist is when you open brand new browser and have never clicked the button if you get me

The option of toggling auto grouping is on the settings page, not the main page. The only way for the user to know is by clicking the group btn and then going to the settings page. 

> if the gear is to switch between pages maybe when on main page have home.icon and when in settings page have gear icon?
Yeah sure we can do that. 

I have also included a link from where I got the icon from in the license.txt file. For instance, the gear icon is under MIT license. I don't really know how to respect the license in extension

**Comment by KaifHalak** [comment]
So far I have implemented the following features (yet to push changes)

--> User can disable auto-grouping completely
--> IF auto-grouping is enabled, users will THEN have the choice of individually disable auto-grouping for certain groups. For ex. if I disable "Youtube" group, any new Youtube tabs will not get grouped (they will stay there as it is)
--> IF auto-grouping is disabled, the above feature is not accessible.

My question:
If a user clicks the group tabs button, all tabs will be grouped regardless if auto-grouping for that group is enabled or not. What do you want to do here???

Once this is resolved, I will start working on the UI

**Comment by AdamKmet1997** [comment]
To answer your question at the end.

There was a situation where my coworker tried the extension and he already had his own groups made before installing the extension

He then clicked the button to group his tabs and that messed up his already made groups.
Maybe we should have a  check to see if there are already any groups made and allow the option to lock them from the start

Group my tabs button should always respect the users preferences, so if I lock that group l/disable auto grouping for that group , the groupy tabs button shouldn't mess with that group


Some users don't group all their tabs based on domain if you get me so if they want to have that group locked nothing should mess with it

That's why I'm thinking we should think a bit more about the design....you can develop the functionality we just need to think about front end functionality a bit so everything is clear

**Comment by KaifHalak** [comment]
Okay, I understand your point. I will pause for now and we can discussion about UI and the features.

I was thinking that maybe when the user clicks on the group tab button, a disclaimer will popup, letting the user know what will happen. We can then advise the user to go to the settings to disable groups from being changed by the extension. We can also implement a "dont show me again" checkbox.

**Comment by KaifHalak** [comment]
UI-1

UI-2

UI-4

UI-3

UI-5

UI-6

UI-7


Any thoughts on the UI?

The size of the extension will increase as more groups are added till 4 rows after which the groups will be moved to a second page. 

I also added a  tool tip when you hover on "?" and the toggle button. 

And added a home icon as well

We can add a similar tool tip when a user hovers on the group tabs button in the main menu

**Comment by AdamKmet1997** [comment]
Idea:
Instead of (?) Can we use fontawesome info icon? Like a little i?

Idea: 
Can all this be on 1 page? Instead of having 2 pages, this would avoid chance if user not knowing there's such functionality available

**Comment by KaifHalak** [comment]
>Instead of (?) Can we use fontawesome info icon? Like a little i?

Sure we can do that

>Can all this be on 1 page? Instead of having 2 pages, this would avoid chance if user not knowing there's such functionality available

Everything is on the first page. I forgot to mention that "Pages" in this context refers to the element with the black border. So when you change pages, you are simply hiding one of those elements and un-hiding another element. Rest remains unchanged if that makes sense

UI-8

This part is what changes when you switch pages

**Comment by AdamKmet1997** [comment]
This is more like what I meant

image


Ignore colours of course just a layout sketch 

Also info icon beside auto group instead of hover so it's more obvious that Theres a hint ?

**Comment by KaifHalak** [comment]
Hmmm... but wont it be like too much information to show a user the moment they open the extension? The user may only interact with "toggling auto grouping" and "disabling certain groups"  once or twice.

**Comment by AdamKmet1997** [comment]
> Hmmm... but wont it be like too much information to show a user the moment they open the extension? The user may only interact with "toggling auto grouping" and "disabling certain groups"  once or twice.

It's like fighting 2 worlds isn't it?

Show all or hide some and they might never find it

If it's all on one page then everything is one click away for user and extension won't become annoying to use?

**Comment by KaifHalak** [comment]
>Show all or hide some and they might never find it 

Maybe the gear icon can indicate that theres more to it?

>If it's all on one page then everything is one click away for user and extension won't become annoying to use?
 
In my opinion the extension would look cleaner if we can separate the "settings" from the group tabs button.

But at the end, its your call

**Comment by AdamKmet1997** [comment]
Sure do it your way, I'm happy to see it that way too.

If we feel it's not working we can implement the other way any time

**Comment by KaifHalak** [comment]
Btw, I'm wondering about my approach to version control. Should I make frequent commits as I make small changes, or would it be better to commit everything at once? The reason I ask is that I've already committed the initial UI design, but after that we had decided to make some changes.  Should I work on a new commit for these changes or amend the existing one?

**Comment by AdamKmet1997** [comment]
> Btw, I'm wondering about my approach to version control. Should I make frequent commits as I make small changes, or would it be better to commit everything at once? The reason I ask is that I've already committed the initial UI design, but after that we had decided to make some changes.  Should I work on a new commit for these changes or amend the existing one?

I prefer to make a commit every time I think I made some progress that if the progress is later decided to be bad I can revert back to previous commit and continue on...

Treat you commits as check points at which point your happy to go back a step if something happens...


If you only make one big commit you don't have the advantage to go a step back while still having bulk of work done thats good.


With too frequent and small commits you're then making it hard to create useful check points for yourself if you get me

**Comment by KaifHalak** [comment]
Features Added:
--> Pagination
--> Info icon
--> All clickable UI is accessible by the TAB button (except for the toggle buttons)

[pagination.webm](https://github.com/AdamKmet1997/Group-My-Tabs/assets/131174445/4b730b9c-db24-4788-9f4c-7149c1ac9bbe)

Issues:
--> When you switch pages, the height will change. In my opinion it kinda feels annoying to move the cursor to change the page. What do you think about it?

**Comment by AdamKmet1997** [comment]
> Features Added:
> --> Pagination
> --> Info icon
> --> All clickable UI is accessible by the TAB button (except for the toggle buttons)
> 
> [pagination.webm](https://github.com/AdamKmet1997/Group-My-Tabs/assets/131174445/4b730b9c-db24-4788-9f4c-7149c1ac9bbe)
> 
> Issues:
> --> When you switch pages, the height will change. In my opinion it kinda feels annoying to move the cursor to change the page. What do you think about it?
> 
> 

I don't think that's annoying, looks great. It would be more annoying if there was big empty box with one group in it...great job


Is this MR ready for review or are you still working on it

**Comment by KaifHalak** [comment]
> I don't think that's annoying, looks great. It would be more annoying if there was big empty box with one group in it

Ig you're right

>great job

Thx!

>Is this MR ready for review or are you still working on it

I just need to clean the code a bit, add minor touches and add an info circle or some sort of indication to the group my tabs button, letting the user know what will happen.

**Comment by AdamKmet1997** [comment]
Perfect

**Comment by KaifHalak** [comment]
I have a small piece of code to create dummy groups for testing purposes. Should I remove it?

**Comment by KaifHalak** [comment]
Okay the extension is ready and I did some light testing.

Just a small heads-up 👀:

I was exploring Font Awesome and found out that I'd need an account to use their icons (based on my research). So, I insetad used svgs from [svg repo](https://www.svgrepo.com/). One of the icons has an MIT license, and the other has a CC Attribution License (I have linked the icons in a .txt file in the Icons folder) . So how can we respect these licenses in the extension?

Also, if you get time, can you please give feedback on my code 😉?

**Comment by KaifHalak** [comment]
Ok so I found an issue when using the extension. 
To exclude certain groups from being grouped, their ids are stored using Chrome's Storage API.
The issue is that when you restart your chrome (and have "Continue where you left off" feature), the groups are "recreated", which means their ids also change. So you will have to once again go the extension and disable the extension....

**Comment by AdamKmet1997** [comment]
> Okay the extension is ready and I did some light testing.
> 
> Just a small heads-up 👀:
> 
> I was exploring Font Awesome and found out that I'd need an account to use their icons (based on my research). So, I insetad used svgs from [svg repo](https://www.svgrepo.com/). One of the icons has an MIT license, and the other has a CC Attribution License (I have linked the icons in a .txt file in the Icons folder) . So how can we respect these licenses in the extension?
> 
> Also, if you get time, can you please give feedback on my code 😉?

Perfect I'll review it over the next few days

**Comment by AdamKmet1997** [comment]
> Ok so I found an issue when using the extension. 
> To exclude certain groups from being grouped, their ids are stored using Chrome's Storage API.
> The issue is that when you restart your chrome (and have "Continue where you left off" feature), the groups are "recreated", which means their ids also change. So you will have to once again go the extension and disable the extension....

Hmmmmmm interesting issue....could we compare old names and new names after reopen and "guess" their previous state if we lost IDs..


How about beside the name we add number that will have display hidden so not visible to user but it will be our way of tracking ID of a group when browser reopens

**Comment by KaifHalak** [comment]
>How about beside the name we add number that will have display hidden so not visible to user but it will be our way of tracking ID of a group when browser reopens

Sorry I didnt get you

One thing I noticed is that the color of the groups remain the same.... so maybe we can use a combination of group's name and color to uniquely identify the groups.

**Comment by AdamKmet1997** [comment]
> >How about beside the name we add number that will have display hidden so not visible to user but it will be our way of tracking ID of a group when browser reopens
> 
> Sorry I didnt get you
> 
> One thing I noticed is that the color of the groups remain the same.... so maybe we can use a combination of group's name and color to uniquely identify the groups.

Meant an invisible to user number beside the name of the group that would be our way of tracking groups
YouTube 1 but user can't see the 1.

But we can track the 1 and when you re open the chrome we can check previous state of 1



Or even better


Add invisible to user 
0 Locked
1 unlocked

And we just toggle this number depending how n the state of the group

And when they re open browser we check the number  and make it that state

**Comment by KaifHalak** [comment]
Ahhh Ok Ok yea thats a good idea. I will implement it

**Comment by KaifHalak** [comment]
> > > How about beside the name we add number that will have display hidden so not visible to user but it will be our way of tracking ID of a group when browser reopens
> > 
> > 
> > Sorry I didnt get you
> > One thing I noticed is that the color of the groups remain the same.... so maybe we can use a combination of group's name and color to uniquely identify the groups.
> 
> Meant an invisible to user number beside the name of the group that would be our way of tracking groups YouTube 1 but user can't see the 1.
> 
> But we can track the 1 and when you re open the chrome we can check previous state of 1
> 
> Or even better
> 
> Add invisible to user 0 Locked 1 unlocked
> 
> And we just toggle this number depending how n the state of the group
> 
> And when they re open browser we check the number and make it that state


Hmm I thought more deeply into this solution. 

The issue is not of tracking whether a group has been disabled or not, the issue is of identifying the groups. Even if we use our own ids (1 , 2, 3), how would we know which id represents which group on chrome startup? Maybe instead of using ids, we can identify the groups by the group map? (but the issue with that solution is that the group map will need to be updated constantly every time a domain leaves or enters a group)

**Comment by AdamKmet1997** [comment]
I'm not sure then seems like you know the most about the problem/solution so I trust you make the best decision

**Comment by KaifHalak** [comment]
Hey, did you go through the code? I'm finding it a bit troublesome to find a solution to the problem. All of the solutions which I come up with don't work in some scenarios which is annoying. I tried using ChatGPT, but to no avail. Maybe we can brainstorm some ideas?

**Comment by AdamKmet1997** [comment]
Hi no, generally there isnt a code review until you say that the code is ready and won't be pushing new changes...once you're happy with the code then I can review it.

If you can't solve that edge case let's get this reviewed and merged and we can attack it later 

It's not really a day to day big so it's ok

**Comment by KaifHalak** [comment]
>Hi no, generally there isnt a code review until you say that the code is ready and won't be pushing new changes...once you're happy with the code then I can review it.

Ahh Ok, didn't know that.

Then the code is ready for review.

**Comment by AdamKmet1997** [comment]
So im plying with this and when i click auto grouping off and open new youtube it auto groups it

also it auto groups if i turn off youtube on its own

image

above is selected and youtube stiull gets auto grouped
 
[screen-capture (1).webm](https://github.com/AdamKmet1997/Group-My-Tabs/assets/32263448/83458362-f4ec-4b63-a491-b032a049b714)

Before I review the code fully, it would be better if this can be addressed I guess

**Comment by KaifHalak** [comment]
Did you remove and reload the extension?
Because there is a piece of code which initializes the settings when the extension is first installed. So I don't think that function fired. Maybe try to remove it and reload it?

**Comment by AdamKmet1997** [comment]
> Did you remove and reload the extension? Because there is a piece of code which initializes the settings when the extension is first installed. So I don't think that function fired. Maybe try to remove it and reload it?

Hi, sorry i wasnt away on Holidays.... I did what you suggested and it seemed to helped/work.... im happy with it works :)


One thing i noticed is that when you create new Group by pressing Group my tabs and straight away got to settings section, the group isnt visible to be locked, instead you have to reopen the extension and then there it is...minor thing and im happy to merge this in and log that as a bug

**Review by AdamKmet1997 — APPROVED** [review]
Happy enough with this to be merged in, few small things that can be fixed as part of bug fixing

**Comment by KaifHalak** [comment]
> Hi, sorry i wasnt away on Holidays

No worries, I hope u enjoyed them :)

>One thing i noticed is that when you create new Group by pressing Group my tabs and straight away got to settings section, the group isnt visible to be locked, instead you have to reopen the extension and then there it is...minor thing and im happy to merge this in and log that as a bug

👍

**Pull request merged**
